; *****************
; Идентификаторы банков
; *****************

; текстовые строки
BANK_DATA_TEXT		= $00

; текстовые строки
BANK_SPRITES_LETTERS = $01

; Задники 1,2,7
BANK_SPRITES_ENV_1_2_7 = $02

; Задники 3,4,5
BANK_SPRITES_ENV_3_4_5	= $03

; Задники 6,8
BANK_SPRITES_ENV_6_8	= $04

; Задники 6,8
BANK_SPRITES_INTERFACE	= $05

; Катсцены
BANK_SPRITES_CUTSCENE	= $06
; Катсцены
BANK_SPRITES_TITLE	= $07

; Тайлмапы 1
BANK_TILEMAPS_01 = $08
; Банк для палитр
BANK_PALETTES_01 = $09

; Тайлмапы 2
BANK_TILEMAPS_02 = $0A
; Тайлмапы 3
BANK_TILEMAPS_03 = $0B

