; *****************
; Идентификаторы банков
; *****************

; текстовые строки
BANK_DATA_TEXT		= $00

; текстовые строки
BANK_SPRITES_LETTERS = $01

; Задники 1,2,7
BANK_SPRITES_ENV_1_2_7 = $02

; Задники 3,4,5
BANK_SPRITES_ENV_3_4_5	= $03

; Задники 6,8
BANK_SPRITES_ENV_6_8	= $04

; Задники 6,8
BANK_SPRITES_INTERFACE	= $05

; Катсцены
BANK_SPRITES_CUTSCENE	= $06
; Катсцены
BANK_SPRITES_TITLE	= $07

; Заглушка под банк
BANK_DATA_08	= $08
; Заглушка под банк
BANK_DATA_09	= $09


; Функции текстового движка
BANK_PRG_TEXT_ENGINE = $A

; Функции(другие)
BANK_PRG_2 = $B
